### ISSUE TITLE
yaml copy paste

### ISSUE THREAD

**Issue by exenza** [aws-samples/serverless-tasks-webapp#6] opened 2022-03-11 14:21 UTC
In Windows 10 using Firefox, copy yaml in workshop, paste in cloud9, whitespaces and indentation is wrong and requires tedious corrections which lead anyway to the template to compile and build.

I suggest to invite users to download the template.yaml file, edit it locally and upload to cloud9

**Comment by mrichman** [comment] 2022-03-11 14:30
Can you tell me on which step in the workshop this is happening?

**Comment by exenza** [comment] 2022-03-11 14:55
Step 1
- [Define a DynamoDB table]
Add the DynamoDB table to the SAM templateHeader anchor link

- [Create a Lambda function]
Create a Lambda function

**Comment by mrichman** [comment] 2022-03-28 17:29
Unable to reproduce. Closing.

**Closed by mrichman** 2022-03-28 17:29 UTC
